import 'package:alto_staffing/MultiSelectDialogItem.dart';

class AltoUtils {

   static const String baseApiUrl = 'http://192.168.1.98:8080/api/mobile';
   //static const String baseApiUrl = 'http://altowebbapp.com:8080/api/mobile';
   static const String baseHcsUrl = 'https://ctms.contingenttalentmanagement.com/CirrusConcept/clearConnect/2_0/index.cfm';
   static const String suCreds = '&username=rsteele&password=altoApp1!';

   static getCerts() {
     return [
       'BSN',
       'RN',
       'LPN',
       'STNA',
       'PA',
       'NP',
       'PT',
       'OT',
       'SLP',
       'COTA',
       'PTA',
       'MLT',
       'RAD Tech',
       'CMA',
       'RMA',
       'Phlebot',
       'LSW/LPC',
       'LISW/LPCC',
       'RT',
       'Medical Receptionist',
       'OB',
       'Dietary',
       'Security',
       'Office Manager',
       'MA',
       'Medical Office',
       'Billing',
       'Med. Records',
       'Accounting',
       'Pharm Tech',
       'Surg Tech',
       'Histologic Tech',
       'Case Management',
       'MT',
       'Pulm Testing',
       'Customer Service',
       'Administrative Assistant',
       'Dental Assistant',
       'Dental Hygienist',
       'Therapist II',
       'Therapist III',
       'Therapist II/III',
       'Support Staff',
       'Dialysis',
       'Clinc',
       'Coder',
       'CNA',
       'Finance & Accounting',
       'Information Technology',
       'Claims Processor',
       'Opthamology Tech',
       'Credentialing ',
       'Data Entry',
       'Endo Tech',
       'Sterile Processing Tech',
       'LCDC',
       'Labor and Delivery',
       'Operating Room ',
       'Family Practice Nurse Practitioner',
       'Psychiatric Nurse Practitioner',
       'Acute Care Nurse Practitioner',
       'CSTech',
       'Imaging Tech',
       'Ultrasonographer',
       'RHIT',
       'Masters Health Care Administration',
       'MBA',
       'Research Assistant',
       'Lab Technician',
       'Pharmacist',
       'Admin',
       'Sales',
       'NONE',
       'STNA Temp to Hire',
       'LPN Temp To Hire',
       'RN Temp To Hire',
       'Transcriptionist',
       'RN Supervisor',
       'Registered Clinical Medical Assistant',
       'Registered EKG Specialist',
       'Registered Phlebotomy Specialist',
       'NA',
       'NRCMA',
       'Home Health Aide',
       'Sleep Tech',
       'EMT',
       'Cert. Phleb',
       'Staffing Coordinator',
       'STNA Orientation',
       'Scheduler',
       'Phone Operator',
       'RN Travel',
       'STNA Oncall',
       'RN Oncall',
       'LPN On Call',
       'Therapy',
       'Tech',
       'Cath Lab',
       'See Specialty',
       'LPN Travel',
       'CVOR Tech',
       'Allied',
       'Postpardum',
       'RN Oct - March',
       'RN II April-Sept',
       'RN III April-Sept',
       'RN Cath Lab Summer',
       'RN I Oct-March',
       'RN II Oct-March',
       'RN III Oct - Sept',
       'RN Cath Lab Winter',
       'RN Orientation Lifecare',
       'Radiology',
       'LSW',
       'LPC',
       'CRNA',
       'Sterile Processor',
       'RN @ LPN Rate',
       'CCMA',
       'LISW/LPCC/LICDC',
       'Clerical',
       'Entry Level Clerical',
       'STNA Incentive Pay',
       'STNA AGS new',
       'LPN AGS - New',
       'RN AGS - New',
       'LPN Incentive Pay',
       'CNA / STNA',
       'Sitter Non-Certified'
     ];
   }

    static getSpecs() {
      return [
        'MA 8+ yrs exp',
        'MA 3-7 yrs exp',
        'ER',
        'ICU',
        'CCU',
        'Tele',
        'Med/Surg',
        'OR',
        'Post-Op',
        'PACU',
        'Pre-Op',
        'Float',
        'Rehab',
        'Ortho',
        'Cardio',
        'Onocology',
        'CVICU',
        'Out-PT',
        'Acute',
        'LTAC',
        'Peds',
        'Geriatric',
        'Home Care',
        'Doc Office',
        'HOSPICE',
        'MRDD',
        'Mental Health',
        'Burns',
        'Drug',
        'Alcohol',
        'MICU',
        'SICU',
        'MACU',
        'ACU',
        'GI Lab',
        'Step down',
        'Or-Scrub',
        'Pulm',
        'Trauma',
        'Renal',
        'Family Health',
        'Discharge Planning',
        'LTC',
        'OB',
        'Labor & Delivery',
        'Behavioral Health',
        'Neuro',
        'Myofascial Release',
        'Wound Care',
        'Kinesio Taping',
        'SNF',
        'ECF',
        'Sub-Acute',
        'ATC',
        'Sports Medicine',
        'Hospital',
        'CLT',
        'Work Hardening',
        'Cognitive Retaining',
        'Chronic Pain Management',
        'Outpatient Rehab',
        'Pharmacy',
        'Out-Pat Surgery',
        'Case Management',
        'PTO',
        'Low census',
        'Administrative Assistant',
        'Customer Service',
        'Medical Assistant',
        'Dental Assistant',
        'Dental Hygienist',
        'X-Ray License',
        'Outpatient',
        'Medical Transcriptionist',
        'Therapist II',
        'Therapist III',
        'Associate Therapists',
        'Therapist II/III',
        'Support Staff',
        'Dialysis',
        'Clinic',
        'Medical Office',
        'Coder',
        'Claims',
        'CNA',
        'Mother Baby',
        'Cardiac Cath Lab',
        'Finance and Accounting',
        'Information Technology',
        'Opthamology Tech',
        'Data Entry',
        'NICU I',
        'NICU II/III',
        'MA 0-2 yrs exp',
        'On Call',
        'Urgent Care',
        'Vascular',
        'Health Info Tech',
        'Epidemiology',
        'Psychiatric',
        'Med/Tel',
        'Admin',
        'Sales',
        'Assisted Living',
        'LPN Temp to Hire',
        'RN Temp To Hire',
        'Cert. Phleb.',
        'Sitter',
        'MA 6-9 yrs. exp.',
        'MA 10+ years',
        'Orientation',
        'Orientation 2',
        'MA 3-5 yrs exp',
        'MA',
        'Cook',
        'Class',
        'RN < 5 years exp',
        'RN 5 + yrs exp.',
        'Electrophysiology Lab/ EP Lab',
        'OnCall STNA',
        'LPN On Call',
        'CVOR',
        'Cath Lab RN',
        'OT',
        'PT',
        'OTA',
        'PTA',
        'SLP',
        'Rad Tech',
        'IR Tech',
        'CT Tech',
        'See Description',
        'PCU',
        'ORT',
        'Infusion',
        'Stepdown',
        'Long Term Care',
        'Sleep Tech',
        'RT',
        'Cath Lab Tech',
        'First Assist',
        'Interventional Radiology',
        'MS Tele',
        'Endoscopy',
        'Antepartum',
        'Flight RN',
        'Postpardum',
        'RN Cath Lab Winter',
        'PICU',
        'Lab',
        'Nurse Anesthetist',
        'Infection Control',
        'Nurse Manager',
        'Employee Health',
        'RN Supervisor',
        'RN Charge',
        'Surg Tech',
        'RNFA',
        'LISW/LPCC/LICDC',
        'Public Health',
        'Office Staff',
        'Incentive pay',
        'STNA1',
        'STNA2',
        'Occupational Health',
      ];
   }

}